-- Stephen Cheney sac295 4275535 --
-- Olympic Game Project --

---DROP ALL TABLES TO MAKE SURE THE SCHEMA IS CLEAR
DROP TABLE USER_ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE USER_ROLE CASCADE CONSTRAINTS;
DROP TABLE PARTICIPANT CASCADE CONSTRAINTS;
DROP TABLE TEAM CASCADE CONSTRAINTS;
DROP TABLE TEAM_MEMBER CASCADE CONSTRAINTS;
DROP TABLE OLYMPICS CASCADE CONSTRAINTS;
DROP TABLE COUNTRY CASCADE CONSTRAINTS;
DROP TABLE SPORT CASCADE CONSTRAINTS;
DROP TABLE EVENT CASCADE CONSTRAINTS;
DROP TABLE VENUE CASCADE CONSTRAINTS;
DROP TABLE MEDAL CASCADE CONSTRAINTS;
DROP TABLE SCOREBOARD CASCADE CONSTRAINTS;
DROP TABLE EVENT_PARTICIPATION CASCADE CONSTRAINTS;
--DROP TABLE RECORDS CASCADE CONSTRAINTS;
/
-- CREATING USER_ACCOUNT TABLE
CREATE TABLE USER_ACCOUNT(
user_id integer not null,
username varchar2(20) not null,
passkey varchar2(20), -- When USER is creating Guest account, passkey will be left blank and Trigger will update passkey upon creation
role_id integer,
last_login date,
CONSTRAINT USER_ACCOUNT_PK PRIMARY KEY (user_id) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT USER_ACCOUNT_UN1 UNIQUE(user_id,username) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT USER_ACCOUNT_UN2 UNIQUE(user_id,username,passkey) INITIALLY IMMEDIATE DEFERRABLE
);/

-- CREATING USER_ROLE TABLE
CREATE TABLE USER_ROLE(
role_id integer not null,
role_name varchar2(20),
CONSTRAINT USER_ROLE_PK PRIMARY KEY (role_id) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT USER_ROLE_UN UNIQUE(role_id,role_name) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT USER_ROLE_NAME_CHK CHECK (role_name = 'Organizer' OR role_name = 'Coach' OR role_name = 'Guest')
);/

-- CREATING PARTICIPANT TABLE
CREATE TABLE PARTICIPANT(
participant_id integer not null,
fname varchar2(30),
lname varchar2(30),
nationality varchar2(20),
birth_place varchar2(40),
dob date,
CONSTRAINT PARTICIPANT_PK PRIMARY KEY (participant_id) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT PARTICIPANT_UN1 UNIQUE(participant_id,fname,lname,dob) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT PARTICIPANT_UN2 UNIQUE(participant_id,fname,lname,dob,birth_place) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT PARTICIPANT_UN3 UNIQUE(participant_id,fname,lname,dob,birth_place,nationality) INITIALLY IMMEDIATE DEFERRABLE
);/

-- CREATING TEAM TABLE
CREATE TABLE TEAM(
team_id integer not null,
olympic_id integer not null,
team_name varchar2(50) not null,
country_id integer not null,
sport_id integer not null,
coach_id integer not null,
CONSTRAINT TEAM_PK PRIMARY KEY (team_id) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT TEAM_UN1 UNIQUE(team_id,olympic_id) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT TEAM_UN2 UNIQUE(team_id,olympic_id,team_name) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT TEAM_UN3 UNIQUE(team_id,olympic_id,team_name,coach_id) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT TEAM_UN4 UNIQUE(team_id,olympic_id,team_name,coach_id,sport_id) INITIALLY IMMEDIATE DEFERRABLE
);/

-- CREATING TEAM_MEMBER TABLE
CREATE TABLE TEAM_MEMBER(
team_id integer not null,
participant_id integer not null,
CONSTRAINT TEAM_MEMBER_UN UNIQUE(team_id,participant_id) INITIALLY IMMEDIATE DEFERRABLE
);/

-- CREATING OLYMPICS TABLE
CREATE TABLE OLYMPICS(
olympic_id integer not null,
olympic_num varchar2(30),
host_city varchar2(30),
opening_date date not null,
closing_date date not null,
official_website varchar2(50),
CONSTRAINT OLYMPICS_PK PRIMARY KEY (olympic_id) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT OLYMPICS_UN1 UNIQUE(olympic_num) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT OLYMPICS_UN2 UNIQUE(olympic_id,olympic_num) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT OLYMPICS_DATE_CHK CHECK (opening_date < closing_date)
);/

-- CREATING COUNTRY TABLE
CREATE TABLE COUNTRY(
country_id integer not null,
country varchar2(20),
country_code varchar2(3),
CONSTRAINT COUNTRY_PK PRIMARY KEY (country_id) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT COUNTRY_UN1 UNIQUE(country_id,country) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT COUNTRY_UN2 UNIQUE(country_id,country,country_code) INITIALLY IMMEDIATE DEFERRABLE
);/

-- CREATING SPORT TABLE
CREATE TABLE SPORT(
sport_id integer not null,
sport_name varchar2(30),
description varchar2(80),
dob date not null,
team_size integer,
CONSTRAINT SPORT_PK PRIMARY KEY (sport_id) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT SPORT_UN1 UNIQUE(sport_id,sport_name) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT SPORT_UN2 UNIQUE(sport_id,sport_name,dob) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT SPORT_UN3 UNIQUE(sport_id,sport_name,dob,team_size) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT SPORT_SIZE_CHK CHECK (team_size >= 1)
);/

-- CREATING EVENT TABLE
CREATE TABLE EVENT(
event_id integer not null,
sport_id integer,
venue_id integer,
gender integer,
event_time date,
CONSTRAINT EVENT_PK PRIMARY KEY (event_id) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT EVENT_UN UNIQUE(event_id,sport_id,venue_id,gender,event_time)INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT EVENT_GENDER_CHK CHECK (gender BETWEEN 0 AND 1) -- Where 0 = male, 1 = female
);/

-- CREATING VENUE TABLE
CREATE TABLE VENUE(
venue_id integer not null,
olympic_id integer not null,
venue_name varchar2(30),
capacity integer,
CONSTRAINT VENUE_PK PRIMARY KEY (venue_id) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT VENUE_UN1 UNIQUE(venue_id,olympic_id) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT VENUE_UN2 UNIQUE(venue_id,olympic_id,venue_name) INITIALLY IMMEDIATE DEFERRABLE
);/

-- CREATING MEDAL TABLE
CREATE TABLE MEDAL(
medal_id integer not null,
medal_title varchar2(6) not null,
points integer not null,
CONSTRAINT MEDAL_PK PRIMARY KEY (medal_id) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT MEDAL_UN1 UNIQUE(medal_id,medal_title) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT MEDAL_UN2 UNIQUE(medal_id,medal_title,points) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT MEDAL_ID_CHK CHECK (medal_id BETWEEN 1 AND 3), -- Where 1 = GOLD, 2 = SILVER, 3 = BRONZE
CONSTRAINT MEDAL_NAME_CHK CHECK (medal_title = 'GOLD' OR medal_title = 'SILVER' OR medal_title = 'BRONZE'),
CONSTRAINT MEDAL_POINTS_CHK CHECK (points BETWEEN 1 AND 3) -- Where 1 = BRONZE, 2 = SILVER, 3 = GOLD
);/

-- CREATING SCOREBOARD TABLE
CREATE TABLE SCOREBOARD(
olympic_id integer not null,
event_id integer not null,
team_id integer,
participant_id integer,
position integer,
medal_id integer,
CONSTRAINT SCOREBOARD_PK PRIMARY KEY (olympic_id, event_id, team_id, participant_id) INITIALLY IMMEDIATE DEFERRABLE
);/

-- CREATING EVENT_PARTICIPATION TABLE
CREATE TABLE EVENT_PARTICIPATION(
event_id integer not null,
team_id integer,
status char,
CONSTRAINT EVENT_PARTICIPATION_PK PRIMARY KEY (event_id,team_id) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT EVENT_PARTICIPATION_STATUS_CHK CHECK (status = 'e' OR status = 'n') -- Where e = eligible, n = non-eligible
);/

-- ADD FOREIGN KEYS
ALTER TABLE TEAM
ADD CONSTRAINT TEAM_FK_OLYMPIC_ID FOREIGN KEY (olympic_id) REFERENCES OLYMPICS(olympic_id) INITIALLY IMMEDIATE DEFERRABLE
ADD CONSTRAINT TEAM_FK_COUNTRY_ID FOREIGN KEY (country_id) REFERENCES COUNTRY(country_id) INITIALLY IMMEDIATE DEFERRABLE
ADD CONSTRAINT TEAM_FK_SPORT_ID FOREIGN KEY (sport_id) REFERENCES SPORT(sport_id) INITIALLY IMMEDIATE DEFERRABLE
ADD CONSTRAINT TEAM_FK_COACH_ID FOREIGN KEY (coach_id) REFERENCES PARTICIPANT(participant_id) INITIALLY IMMEDIATE DEFERRABLE;/

ALTER TABLE TEAM_MEMBER
ADD CONSTRAINT TEAM_MEMBER_FK_TEAM_ID FOREIGN KEY (team_id) REFERENCES TEAM(team_id) INITIALLY IMMEDIATE DEFERRABLE
ADD CONSTRAINT TEAM_MEMBER_FK_PARTICIPANT_ID FOREIGN KEY (participant_id) REFERENCES PARTICIPANT(participant_id) INITIALLY IMMEDIATE DEFERRABLE;/

ALTER TABLE EVENT
ADD CONSTRAINT EVENT_FK_SPORT_ID FOREIGN KEY (sport_id) REFERENCES SPORT(sport_id) INITIALLY IMMEDIATE DEFERRABLE
ADD CONSTRAINT EVENT_FK_VENUE_ID FOREIGN KEY (venue_id) REFERENCES VENUE(venue_id) INITIALLY IMMEDIATE DEFERRABLE;/

ALTER TABLE VENUE
ADD CONSTRAINT VENUE_FK_OLYMPIC_ID FOREIGN KEY (olympic_id) REFERENCES OLYMPICS(olympic_id) INITIALLY IMMEDIATE DEFERRABLE;/

ALTER TABLE SCOREBOARD
ADD CONSTRAINT SCOREBOARD_FK_OLYMPIC_ID FOREIGN KEY (olympic_id) REFERENCES OLYMPICS(olympic_id) INITIALLY IMMEDIATE DEFERRABLE
ADD CONSTRAINT SCOREBOARD_FK_EVENT_ID FOREIGN KEY (event_id) REFERENCES EVENT(event_id) INITIALLY IMMEDIATE DEFERRABLE
ADD CONSTRAINT SCOREBOARD_FK_TEAM_ID FOREIGN KEY (team_id) REFERENCES TEAM(team_id) INITIALLY IMMEDIATE DEFERRABLE
ADD CONSTRAINT SCOREBOARD_FK_PARTICIPANT_ID FOREIGN KEY (participant_id) REFERENCES PARTICIPANT(participant_id) INITIALLY IMMEDIATE DEFERRABLE
ADD CONSTRAINT SCOREBOARD_FK_MEDAL_ID FOREIGN KEY (medal_id) REFERENCES MEDAL(medal_id) INITIALLY IMMEDIATE DEFERRABLE;/

ALTER TABLE EVENT_PARTICIPATION
ADD CONSTRAINT EVEN_PARTICIPATION_FK_EVENT_ID FOREIGN KEY (event_id) REFERENCES EVENT(event_id) INITIALLY IMMEDIATE DEFERRABLE
ADD CONSTRAINT EVEN_PARTICIPATION_FK_TEAM_ID FOREIGN KEY (team_id) REFERENCES TEAM(team_id) INITIALLY IMMEDIATE DEFERRABLE;/

