-- Stephen Cheney sac295 4275535 --
-- Olympic Game Project --

---DROP ALL TABLES TO MAKE SURE THE SCHEMA IS CLEAR
DROP TABLE USER_ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE USER_ROLE CASCADE CONSTRAINTS;
DROP TABLE PARTICIPANT CASCADE CONSTRAINTS;
DROP TABLE TEAM CASCADE CONSTRAINTS;
DROP TABLE TEAM_MEMBER CASCADE CONSTRAINTS;
DROP TABLE OLYMPICS CASCADE CONSTRAINTS;
DROP TABLE COUNTRY CASCADE CONSTRAINTS;
DROP TABLE SPORT CASCADE CONSTRAINTS;
DROP TABLE EVENT CASCADE CONSTRAINTS;
DROP TABLE VENUE CASCADE CONSTRAINTS;
DROP TABLE MEDAL CASCADE CONSTRAINTS;
DROP TABLE SCOREBOARD CASCADE CONSTRAINTS;
DROP TABLE EVENT_PARTICIPATION CASCADE CONSTRAINTS;
commit;
--DROP TABLE RECORDS CASCADE CONSTRAINTS;
/
-- CREATING USER_ACCOUNT TABLE
CREATE TABLE USER_ACCOUNT(
user_id integer not null,
username varchar2(20) not null,
passkey varchar2(20) not null, -- When USER is creating Guest account, passkey will be left blank and Trigger will update passkey upon creation
role_id integer not null,
last_login date not null,
CONSTRAINT USER_ACCOUNT_PK PRIMARY KEY (user_id) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT USER_ACCOUNT_UN1 UNIQUE(user_id,username,role_id) INITIALLY DEFERRED DEFERRABLE, -- may have different account levels with same user/pass
CONSTRAINT USER_ACCOUNT_UN2 UNIQUE(user_id,username,passkey) INITIALLY DEFERRED DEFERRABLE
);
/
commit;
-- CREATING USER_ROLE TABLE
CREATE TABLE USER_ROLE(
role_id integer not null,
role_name varchar2(20) not null,
CONSTRAINT USER_ROLE_PK PRIMARY KEY (role_id) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT USER_ROLE_UN UNIQUE(role_id,role_name) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT USER_ROLE_NAME_CHK CHECK (role_name = 'Organizer' OR role_name = 'Coach' OR role_name = 'Guest')
);
/
commit;
-- CREATING PARTICIPANT TABLE
CREATE TABLE PARTICIPANT(
participant_id integer not null,
fname varchar2(30) not null,
lname varchar2(30) not null,
nationality varchar2(20) not null,
birth_place varchar2(40) not null,
dob date not null,
CONSTRAINT PARTICIPANT_PK PRIMARY KEY (participant_id) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT PARTICIPANT_UN1 UNIQUE(participant_id,fname,lname,dob) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT PARTICIPANT_UN2 UNIQUE(participant_id,fname,lname,dob,birth_place) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT PARTICIPANT_UN3 UNIQUE(participant_id,fname,lname,dob,birth_place,nationality) INITIALLY DEFERRED DEFERRABLE
);
/
commit;
-- CREATING TEAM TABLE
CREATE TABLE TEAM(
team_id integer not null,
olympic_id integer not null,
team_name varchar2(50) not null,
country_id integer not null,
sport_id integer not null,
coach_id integer not null,
CONSTRAINT TEAM_PK PRIMARY KEY (team_id) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT TEAM_UN1 UNIQUE(team_id,olympic_id) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT TEAM_UN2 UNIQUE(team_id,olympic_id,team_name) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT TEAM_UN3 UNIQUE(team_id,olympic_id,team_name,coach_id) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT TEAM_UN4 UNIQUE(team_id,olympic_id,team_name,coach_id,sport_id) INITIALLY DEFERRED DEFERRABLE
);
/
commit;
-- CREATING TEAM_MEMBER TABLE
CREATE TABLE TEAM_MEMBER(
team_id integer not null,
participant_id integer not null,
CONSTRAINT TEAM_MEMBER_UN UNIQUE(team_id,participant_id) INITIALLY DEFERRED DEFERRABLE
);
/
commit;
-- CREATING OLYMPICS TABLE
CREATE TABLE OLYMPICS(
olympic_id integer not null,
olympic_num varchar2(30) not null,
host_city varchar2(30) not null,
opening_date date not null,
closing_date date not null,
official_website varchar2(50),
CONSTRAINT OLYMPICS_PK PRIMARY KEY (olympic_id) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT OLYMPICS_UN1 UNIQUE(olympic_num) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT OLYMPICS_UN2 UNIQUE(olympic_id,olympic_num) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT OLYMPICS_DATE_CHK CHECK (opening_date < closing_date)
);
/
commit;
-- CREATING COUNTRY TABLE
CREATE TABLE COUNTRY(
country_id integer not null,
country varchar2(20) not null,
country_code varchar2(3),
CONSTRAINT COUNTRY_PK PRIMARY KEY (country_id) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT COUNTY_UN1 UNIQUE(country) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT COUNTRY_UN2 UNIQUE(country_code) INITIALLY DEFERRED DEFERRABLE
);
/
commit;
-- CREATING SPORT TABLE
CREATE TABLE SPORT(
sport_id integer not null,
sport_name varchar2(30) not null,
description varchar2(80) not null,
dob date not null,
team_size integer not null,
CONSTRAINT SPORT_PK PRIMARY KEY (sport_id) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT SPORT_UN1 UNIQUE(sport_id,sport_name) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT SPORT_UN2 UNIQUE(sport_id,sport_name,dob) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT SPORT_UN3 UNIQUE(sport_id,sport_name,dob,team_size) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT SPORT_SIZE_CHK CHECK (team_size >= 1)
);
/
commit;
-- CREATING EVENT TABLE
CREATE TABLE EVENT(
event_id integer not null,
sport_id integer not null,
venue_id integer not null,
gender integer not null,
event_time date not null,
CONSTRAINT EVENT_PK PRIMARY KEY (event_id) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT EVENT_UN UNIQUE(event_id,sport_id,venue_id,gender,event_time)INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT EVENT_GENDER_CHK CHECK (gender = 0 OR gender = 1) -- Where 0 = male, 1 = female
);
/
commit;
-- CREATING VENUE TABLE
CREATE TABLE VENUE(
venue_id integer not null,
olympic_id integer not null,
venue_name varchar2(30) not null,
capacity integer not null,
CONSTRAINT VENUE_PK PRIMARY KEY (venue_id) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT VENUE_UN1 UNIQUE(venue_id,olympic_id) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT VENUE_UN2 UNIQUE(venue_id,olympic_id,venue_name) INITIALLY DEFERRED DEFERRABLE
);
/
commit;
-- CREATING MEDAL TABLE
CREATE TABLE MEDAL(
medal_id integer not null,
medal_title varchar2(6) not null,
points integer not null,
CONSTRAINT MEDAL_PK PRIMARY KEY (medal_id) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT MEDAL_UN1 UNIQUE(medal_id,medal_title) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT MEDAL_UN2 UNIQUE(medal_id,medal_title,points) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT MEDAL_ID_CHK CHECK (medal_id BETWEEN 1 AND 3), -- Where 1 = GOLD, 2 = SILVER, 3 = BRONZE
CONSTRAINT MEDAL_NAME_CHK CHECK (medal_title = 'GOLD' OR medal_title = 'SILVER' OR medal_title = 'BRONZE'),
CONSTRAINT MEDAL_POINTS_CHK CHECK (points BETWEEN 1 AND 3) -- Where 1 = BRONZE, 2 = SILVER, 3 = GOLD
);
/
commit;
-- CREATING SCOREBOARD TABLE
CREATE TABLE SCOREBOARD(
olympic_id integer not null,
event_id integer not null,
team_id integer not null,
participant_id integer not null,
position integer not null,
medal_id integer,
CONSTRAINT SCOREBOARD_PK PRIMARY KEY (olympic_id, event_id,team_id,participant_id) INITIALLY DEFERRED DEFERRABLE
)
SEGMENT CREATION IMMEDIATE;
/
commit;
-- CREATING EVENT_PARTICIPATION TABLE
CREATE TABLE EVENT_PARTICIPATION(
event_id integer not null,
team_id integer not null,
status char not null,
CONSTRAINT EVENT_PARTICIPATION_PK PRIMARY KEY (event_id,team_id) INITIALLY DEFERRED DEFERRABLE,
CONSTRAINT EVENT_PARTICIPATION_STATUS_CHK CHECK (status = 'e' OR status = 'n') -- Where e = eligible, n = non-eligible
);
/
commit;
-- ADD FOREIGN KEYS
ALTER TABLE TEAM
ADD CONSTRAINT TEAM_FK_OLYMPIC_ID FOREIGN KEY (olympic_id) REFERENCES OLYMPICS(olympic_id) INITIALLY DEFERRED DEFERRABLE
ADD CONSTRAINT TEAM_FK_COUNTRY_ID FOREIGN KEY (country_id) REFERENCES COUNTRY(country_id) INITIALLY DEFERRED DEFERRABLE
ADD CONSTRAINT TEAM_FK_SPORT_ID FOREIGN KEY (sport_id) REFERENCES SPORT(sport_id) INITIALLY DEFERRED DEFERRABLE
ADD CONSTRAINT TEAM_FK_COACH_ID FOREIGN KEY (coach_id) REFERENCES PARTICIPANT(participant_id) INITIALLY DEFERRED DEFERRABLE;
/
commit;
ALTER TABLE TEAM_MEMBER
ADD CONSTRAINT TEAM_MEMBER_FK_TEAM_ID FOREIGN KEY (team_id) REFERENCES TEAM(team_id) on delete cascade INITIALLY DEFERRED DEFERRABLE
ADD CONSTRAINT TEAM_MEMBER_FK_PARTICIPANT_ID FOREIGN KEY (participant_id) REFERENCES PARTICIPANT(participant_id) on delete cascade INITIALLY DEFERRED DEFERRABLE;
/
commit;
ALTER TABLE EVENT
ADD CONSTRAINT EVENT_FK_SPORT_ID FOREIGN KEY (sport_id) REFERENCES SPORT(sport_id) INITIALLY DEFERRED DEFERRABLE
ADD CONSTRAINT EVENT_FK_VENUE_ID FOREIGN KEY (venue_id) REFERENCES VENUE(venue_id) INITIALLY DEFERRED DEFERRABLE;
/
commit;
ALTER TABLE VENUE
ADD CONSTRAINT VENUE_FK_OLYMPIC_ID FOREIGN KEY (olympic_id) REFERENCES OLYMPICS(olympic_id) INITIALLY DEFERRED DEFERRABLE;
/
commit;
ALTER TABLE SCOREBOARD
ADD CONSTRAINT SCOREBOARD_FK_OLYMPIC_ID FOREIGN KEY (olympic_id) REFERENCES OLYMPICS(olympic_id) INITIALLY DEFERRED DEFERRABLE
ADD CONSTRAINT SCOREBOARD_FK_EVENT_ID FOREIGN KEY (event_id) REFERENCES EVENT(event_id) INITIALLY DEFERRED DEFERRABLE
ADD CONSTRAINT SCOREBOARD_FK_TEAM_ID FOREIGN KEY (team_id) REFERENCES TEAM(team_id) on delete cascade INITIALLY DEFERRED DEFERRABLE
ADD CONSTRAINT SCOREBOARD_FK_PARTICIPANT_ID FOREIGN KEY (participant_id) REFERENCES PARTICIPANT(participant_id) INITIALLY DEFERRED DEFERRABLE
ADD CONSTRAINT SCOREBOARD_FK_MEDAL_ID FOREIGN KEY (medal_id) REFERENCES MEDAL(medal_id) INITIALLY DEFERRED DEFERRABLE;
/
commit;
ALTER TABLE EVENT_PARTICIPATION
ADD CONSTRAINT EVENT_PART_FK_EVENT_ID FOREIGN KEY (event_id) REFERENCES EVENT(event_id) INITIALLY DEFERRED DEFERRABLE
ADD CONSTRAINT EVENT_PART_FK_TEAM_ID FOREIGN KEY (team_id) REFERENCES TEAM(team_id) on delete cascade INITIALLY DEFERRED DEFERRABLE;
/
commit;
ALTER TABLE USER_ACCOUNT
ADD CONSTRAINT USER_ACCOUNT_FK_ROLE_ID FOREIGN KEY (role_id) REFERENCES USER_ROLE(role_id) INITIALLY DEFERRED DEFERRABLE;
/
commit;
ALTER TABLE PARTICIPANT
ADD CONSTRAINT PARTICIPANT_FK_NATIONALITY FOREIGN KEY (nationality) REFERENCES COUNTRY(country) INITIALLY DEFERRED DEFERRABLE;
/

commit;
/